### ISSUE TITLE
Reduced block gas limit when `TxPermission.limitBlockGas()` returns `true`

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#119]
I performed a few stress tests in the scope of https://github.com/poanetwork/posdao-test-setup/issues/40 and concluded that [the limitations I outlined there](https://github.com/poanetwork/posdao-test-setup/issues/40#issuecomment-480864549) are only actual for the almost empty blocks.

It means that we can't overload the blocks by transactions when there is a snapshotting or rewarding process is being done. These processes are performed at the end of staking epoch (during the last [MAX_VALIDATORS](https://github.com/poanetwork/posdao-contracts/blob/52031378a0d48261f7d41e1574294d25a05546c7/contracts/abstracts/ValidatorSetBase.sol#L18) * [DELEGATORS_ALIQUOT](https://github.com/poanetwork/posdao-contracts/blob/52031378a0d48261f7d41e1574294d25a05546c7/contracts/abstracts/BlockRewardBase.sol#L18) blocks) and at the beginning of a new staking epoch (during the same amount of blocks).

I.e., for default values of the MAX_VALIDATORS and DELEGATORS_ALIQUOT constants there are `~80` blocks per staking epoch (which length is `120960` blocks) should almost be empty (not overloaded by transactions) when the staking epoch ends, and a new staking epoch begins.

I've added a special [`limitBlockGas()`](https://github.com/poanetwork/posdao-contracts/blob/3b5db5f74082da96c161dec0010105078d2f4b81/contracts/TxPermission.sol#L181) getter to the `TxPermission` contract which returns `true` when we need to have a limited block gas limit (I propose to set it to `2 000 000`) and returns `false` when block gas limit should be normal.

I expect that when a validator is going to create a new block, it should first call the `limitBlockGas()` and check the returned value: if it is `true`, the newly created block should be limited to `2 000 000` of gas.

So, we will have `~0,066%` of limited blocks per staking epoch. We need this to ensure that the network is stable. Otherwise, the block time can exceed 5-6 seconds AuRa limit for those `80` blocks.

**Comment by afck** [comment]
Shouldn't the snapshotting and rewarding transactions be at the beginning of the block anyway? And can't we just fill up the rest of the block with user transactions then?

**Comment by varasev** [comment]
> Shouldn't the snapshotting and rewarding transactions be at the beginning of the block anyway? And can't we just fill up the rest of the block with user transactions then?

This wouldn't help us because the snapshotting and rewarding operations take a part of block's time anyway.

**Comment by afck** [comment]
I'll try to find out how to do that and take notes here.

The `BlockGasLimitReached` error is created only in [`Executive::transact_with_tracer`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/executive.rs#L836), which uses the [`EnvInfo::gas_limit`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/vm/src/env_info.rs#L42) from [`Executive::info`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/executive.rs#L748).

[`Miner::prepare_block` runs transactions](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/miner/miner.rs#L480) by calling [`OpenBlock::push_transaction`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/block.rs#L330), which [creates an `EnvInfo`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/block.rs#L135) using the header's gas limit.

The header is created in [`OpenBlock::new`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/block.rs#L255), which calls [`ExecutedBlock::new`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/block.rs#L271), which just [creates a default header](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/block.rs#L119). It then calls [several methods of `Machine` and `Engine`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/block.rs#L284).
* [`Machine::populate_from_parent`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/machine.rs#L232) takes the gas limit from the parent and applies a few calculations to apply gas limit targets and bounds. That complicates things because it means we have to explicitly set the gas limit back to normal after the 80 blocks.
* In [`Engine::populate_from_parent`](https://github.com/poanetwork/parity-ethereum/blob/414ab08fddc79ea91df3c83bb35d919044bed784/ethcore/src/engines/authority_round/mod.rs#L985), we have the opportunity to overwrite the `Machine`'s choice. Unfortunately this method currently only gets the headers, not the blocks. But probably calling `limitBlockGas` via `self.client` should yield the correct result?
* Both `on_new_block` methods don't seem to touch the gas limit.

So I think `Engine::populate_from_parent` would be the right place to do this, but I'm still confused by the complicated gas limit calculation. (Also, if we store the old gas limit in the engine, and restore it after the 80 blocks, could that cause problems if there's a reorg?)

**Comment by varasev** [comment]
AFAIK, the initial block gas limit is set for the genesis https://github.com/poanetwork/posdao-contracts/blob/3b5db5f74082da96c161dec0010105078d2f4b81/templates/spec.json#L46 and then reduced every block (I think the `gasLimitBoundDivisor` option participates in this: https://github.com/poanetwork/posdao-contracts/blob/3b5db5f74082da96c161dec0010105078d2f4b81/templates/spec.json#L24 - see https://wiki.parity.io/Chain-specification.html) until the `gas_floor_target` is reached (which is `8000000` by default).

**Comment by afck** [comment]
This will require much more invasive changes than I'd hoped: The block verification code will [produce an `InvalidGasLimit` error](https://github.com/poanetwork/parity-ethereum/blob/86446a0923464c3ed16615914d5940211369be8c/ethcore/src/verification/verification.rs#L355) not only if a block's gas limit is below the configured minimum (which we could set to `2_000_000`), but also if it differs too much from the parent block's gas limit!

Fortunately we have access to the `EthEngine` in both places, so we could add yet another method (`gas_limit_override`?) to that, and add an exception to the verification code whenever the engine says so. In a block where `limitBlockGas()` returns `false` again, that method could either return some fixed value (`min_gas_limit`?), or find the latest ancestor where `limitBlockGas()` was also `false` and continue with that ancestor's gas limit. The former would be much easier, and sufficient for our use case, I think—or do we need to allow the validators to "vote" on changing the gas limit?

**Comment by varasev** [comment]
> or do we need to allow the validators to "vote" on changing the gas limit?

What do you mean by voting here?

**Comment by afck** [comment]
> What do you mean by voting here?

If I understand correctly, the whole logic of having upper and lower bounds and allowing blocks to gradually change the gas limits between those is so that the miners can choose to adapt it: Whenever you mine a block, you can slightly increase or decrease the gas limit, so over time it goes up if more miners want it to go up and vice versa.

**Comment by vkomenda** [comment]
@varasev, just to confirm: we cannot have a contract method return the block gas limit? Probably that would be less secure than having a hardcoded reduced block gas limit?

If we had a method returning the gas limit then we could implement gas limit changes using on-chain governance and probably the implementation could be simplified.

**Comment by varasev** [comment]
@vkomenda it depends on what implementation we need for such a method in a contract.

At the moment we have the [`TxPermission.limitBlockGas()`](https://github.com/poanetwork/posdao-contracts/blob/0b478be2b0e5db06cce0a3ac94982f47bc0bde73/contracts/TxPermission.sol#L202-L219) public getter which returns `true` or `false`.

Instead of that, we could rename it to `blockGasLimit` and make it return `uint256` value of the current gas limit: in case of `true` it would return `2 000 000`, in case of `false` it would return `10 000 000`.

But I'm not sure that the immediate change of the block gas limit (when, for example, a block `300` has `10 000 000`, but the next block `301` has `2 000 000`) is a secure solution because the standard Parity approach assumes that the block gas limit should be changed smoothly according to the `gas_floor_target` config parameter. But if my fears are groundless, then yes, we could implement such a method in a contract as I described above.

**Comment by afck** [comment]
I like that solution. I don't really see the benefit of the smoothly changing gas limit in our use case anyway, and having two fixed values actually sounds safer to me in the context of Aura.

**Comment by vkomenda** [comment]
@afck, do you like `blockGasLimit` more than `limitBlockGas`? :)

**Comment by varasev** [comment]
Added the `blockGasLimit` public getter: https://github.com/poanetwork/posdao-contracts/commit/fdaa685de851378b35741bdab986414dfd9042b1

**Comment by afck** [comment]
> do you like `blockGasLimit` more than `limitBlockGas`? :)

I do, yes: The latter sounds a bit like it would allow you to _set_ the block gas limit by calling that function.

**Comment by afck** [comment]
I wonder whether we should move this to a separate contract, at least from Parity's perspective: We could still configure the same address as the transaction permission contract, i.e. use that address twice in the chain spec (no change to the Solidity code required). But at least in the Rust code and conceptually, transaction permission and block gas limit would then be separate.

**Comment by vkomenda** [comment]
> I wonder whether we should move this to a separate contract,

Could this be achieved with different ABIs for the block gas limit without changing the Solidity contract?

**Comment by afck** [comment]
Yes, that's what I mean: No change to solidity, but a separate entry in the chain spec (with the same contract address, if preferred).

**Comment by vkomenda** [comment]
Makes sense, I think.

**Comment by varasev** [comment]
Done in #140. Example of use in `spec.json`:

```
...
"engine": {
    ....
},
"params": {
    ....
    "blockGasLimitContract" : {
        "10": "0x4000000000000000000000000000000000000001"
    }
}
...
```
