### ISSUE TITLE
Feature Requests for Hbbft Test Network

### ISSUE THREAD

**Issue by c0gent** [poanetwork/parity-ethereum#24]
1. [ ] Parity should generate twenty 32-bit unsigned integer random numbers in the range from 0 to 0xffffffff and pass them into `ReportingValidatorSet` smart contract calling its `storeRandom` function. That function will look like the following:

```
uint256[] public currentRandom;

modifier onlySystem() {
    require(msg.sender == 0xffffFFFfFFffffffffffffffFfFFFfffFFFfFFfE);
    _;
}

function storeRandom(uint256 _random[]) public onlySystem {
    currentRandom.length = 0;
    for (uint256 i = 0; i < _random.length; i++) {
        currentRandom.push(_random[i]);
    }
}
```

The `storeRandom` should be called right before `InitiateChange` event is generated (see below).

2. [ ] Parity should emit `InitiateChange` event (described in https://wiki.parity.io/Validator-Set.html) when a current epoch is supposed to be finished and a new epoch is supposed to be started.
According to docs on the page https://wiki.parity.io/Validator-Set.html, the `InitiateChange` event should trigger a calling of `ReportingValidatorSet.finalizeChange()` function which updates validator set.

3. [ ] Parity should call `ReportingValidatorSet.reportMalicious` function (see https://wiki.parity.io/Validator-Set.html#reporting-contract) when one of the validators behaves badly.

4. [x] SYSTEM_ADDRESS should call `reward` function of `BlockReward` smart contract every new block.

`BlockReward` is described in https://wiki.parity.io/Block-Reward-Contract.html

~We don't need to have `address[] benefactors` and `uint16[] kind` parameters on the input of `reward` function because the array of validators will be read from `ReportingValidatorSet` smart contract, but we still need Parity to expect a list of addresses and respective rewards returned by `reward` function.~

**Comment by varasev** [comment]
Please read paragraph 4 as follows:

SYSTEM_ADDRESS should call `reward` function of `BlockReward` smart contract every new block.

`BlockReward` is described in https://wiki.parity.io/Block-Reward-Contract.html

We don't need to have `address[] benefactors` and `uint16[] kind` parameters on the input of `reward` function because the array of validators will be read from `ReportingValidatorSet` smart contract, but we still need Parity to expect a list of addresses and respective rewards returned by `reward` function.

So, Solidity prototype of `reward` function for this case looks like this:

```
interface BlockReward {
// produce rewards for the benefactors,
// read from ValidatorSet contract.
// only callable by `SYSTEM_ADDRESS`
function reward() external returns (address[], uint256[]);
}
```

**Comment by afck** [comment]
Our current implementation calls Parity's [`BlockRewardContract::reward`](https://github.com/poanetwork/parity-ethereum/blob/d614bc8dc72c2dc39d129e4fa15d4d857eae2fd6/ethcore/src/engines/block_reward.rs#L110) method, which does pass in the `benefactors` and `kind`. We can change that, of course, but I'm wondering whether it would be better to change the contract, so that all block reward contract interfaces remain compatible, and all engine-contract combinations work? (I.e. the new contract would just ignore those arguments.)

/cc @DrPeterVanNostrand

**Comment by varasev** [comment]
@afck Sure, we can leave the same interface for `reward` function if it's easier to implement for you:

```
interface BlockReward {
    function reward(address[], uint16[]) external returns (address[], uint256[]);
}
```

In this case, `reward` function would just ignore the input.

**Comment by afck** [comment]
I don't think it would be much work to implement it the other way; it's rather that I think it makes more sense for Parity to keep the block reward contract interfaces consistent, so that all combinations with engines are supported.
But it's just a suggestion—I'm fine with either solution.

**Comment by varasev** [comment]
Ok, let's remove paragraph 4 from the task - I also think it's better to keep universal interface.

**Comment by varasev** [comment]
Sorry guys, the 2nd paragraph is incorrect:

```
Parity should emit InitiateChange event (described in https://wiki.parity.io/Validator-Set.html) when a current epoch is supposed to be finished and a new epoch is supposed to be started.
According to docs on the page https://wiki.parity.io/Validator-Set.html, the InitiateChange event should trigger a calling of ReportingValidatorSet.finalizeChange() function which updates validator set.
```

This mechanism won't work because Parity should pass a new validator set into `InitiateChange` (in the second parameter `_new_set`), but at the moment of its emitting Parity doesn't yet know the list of new validators. The list should be built by ReportingValidatorSet smart contract.

So, I think we should have the next function in `ReportingValidatorSet` contract for defining a new validator set:

```
function newValidatorSet() public onlySystem returns(address[]) {
  // ...
}
```

Parity will call `newValidatorSet()` by SYSTEM_ADDRESS when a new staking epoch is beginning. That function will build and return the array of new validators.

Is it possible?

**Comment by varasev** [comment]
Another way is to have the next function:

```
function requestNewValidatorSet() public onlySystem {
  // ... building a new set ...
  emit InitiateChange(blockhash(block.number - 1), newListOfValidators);
}
```

So, Parity will call `requestNewValidatorSet` by SYSTEM_ADDRESS when a new staking epoch begins (or when the previous epoch finishes). The function will build an array of new validators (`newListOfValidators`) and pass it into `InitiateChange` event.

Parity catches the event, set the list of new validators and calls `finalizeChange` function (all these steps are described in https://wiki.parity.io/Validator-Set.html).

But AFAIK, at the moment events cannot be emitted by system transactions. Is it possible to fix that?

**Comment by c0gent** [comment]
@varasev Perhaps it would be best if you created an issue for each item, that way you could edit them and we could focus the conversations a bit.

**Comment by varasev** [comment]
Ok, I've created the next separated issues:
- https://github.com/poanetwork/parity-ethereum/issues/31
- https://github.com/poanetwork/parity-ethereum/issues/32
- https://github.com/poanetwork/parity-ethereum/issues/33
- https://github.com/poanetwork/parity-ethereum/issues/34

Please close this issue.
