### ISSUE TITLE
Feature request for hbbft: BlockReward

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#31]
`SYSTEM_ADDRESS` should call `reward` function of `BlockReward` smart contract every new block.

`BlockReward` is described in https://wiki.parity.io/Block-Reward-Contract.html

Parity should pass a list of active validators in `benefactors` input array. If a node of a validator is offline, the address of that validator shouldn't be in `benefactors` array.

**Comment by afck** [comment]
> If a node of a validator is offline

Note that with Honey Badger, the new block's transactions magically pop up simulatenously in all the validators, and then they must turn them into the exact same block, so everything they do at that point must be consensus. In particular, my node mustn't exclude someone from the `benefactors` just because they're not currently connected to my node.
Also, Honey Badger's internal list of validators lags a few blocks behind the contract's list.
That means "offline" isn't easy to define; I guess it should mean something like "doesn't take part in the consensus process". There's several aspects to this:

We'll need to decide what exactly to do with "hard" faults, i.e. if a node provably doesn't follow protocol:
* Just inform the user: let them do a ballot and see whether they vote to remove the faulty validator.
* Remove the validator from Honey Badger immediately for a few hours, _and_ inform the user. If there is no ballot after that period and the validator is still in office, add their node back in (and hope they replaced their binary with a malware-free one).

I'm in favor of the second option, I think, because there's no point having a node in the network that has been proven faulty. And I'd exclude them from the `benefactors` for that period, i.e. make the `benefactors` the validators in Honey Badger's sense, rather than the contract's sense.

If a node has a slow or unstable machine or Internet connection, or goes offline permanently, that won't show up as a hard fault; they'll just fail to send messages, and blocks will be produced without their contributions. We could:
* Just only reward the nodes whose contributions got accepted. This would be the easier option but we don't have any real-world data yet about how much that would hurt validators with a just _slightly_ slower connection than the others.
* Make nodes detect who goes offline or didn't send any messages for some period of time. Then they'd need to notify a special smart contract that "`Node 5 is offline!`", and whenever that contract has collected _f + 1_ such messages, we'd consider that a hard fault (see above).

For now I'd just go with the first point: The `benefactors` are exactly the nodes whose contribution got accepted into the block.

(But maybe all that is a moot point anyway: If I understand #24 correctly, we'll use a block reward contract in the end that ignores the parameter?)

/cc @DrPeterVanNostrand

**Comment by varasev** [comment]
> We'll need to decide what exactly to do with "hard" faults, i.e. if a node provably doesn't follow protocol: Remove the validator from Honey Badger immediately for a few hours, and inform the user. If there is no ballot after that period and the validator is still in office, add their node back in (and hope they replaced their binary with a malware-free one).

Please clarify what you mean under ballots. Should there be some smart contract to let the validators create the ballot and give their votes?

> The `benefactors` are exactly the nodes whose contribution got accepted into the block.

Agree. The primary meaning of this issue is to not reward the nodes which didn't take part in the consensus process for the current block.

> If I understand #24 correctly, we'll use a block reward contract in the end that ignores the parameter?

Please close the issue #24 - I divided that into the separated more correct issues listed here: https://github.com/poanetwork/parity-ethereum/issues/24#issuecomment-439799421

Now I think it's better to use `benefactors` input array instead of reading validators list from `ValidatorSet` contract because this contract doesn't know about validators which are not got accepted into the block.

**Comment by afck** [comment]
Right, sorry, I was still thinking of the POA governance contracts! With staking, we'd just remove nodes for the rest of the epoch and [report them as faulty](https://github.com/poanetwork/parity-ethereum/issues/32) if there's a hard fault. (And possibly also if they failed to get their contribution accepted for too many blocks in a row.)

> Now I think it's better to use `benefactors` input array

I agree! :+1:

**Comment by varasev** [comment]
> we'd just remove nodes for the rest of the epoch

Okay.

**Comment by DemiMarie** [comment]
Already fixed.
