### ISSUE TITLE
Call `emitInitiateChange` function by validator

### ISSUE THREAD

**Issue by varasev** [poanetwork/parity-ethereum#71]
(related to https://github.com/poanetwork/parity-ethereum/issues/49)

I've missed one detail:

There can be a case when the validator set is not changed at the beginning of new staking epoch (due to delegators did nothing during the finished staking epoch).

The `getPendingValidators()` getter will return the same set in that case, and as a result, the `finalizeChange()` function won't be called by Parity (because the set wasn't changed).

But we need to call `finalizeChange()` anyway when the new staking epoch begins.

Can we use the `changeRequestCount()` getter instead of `getPendingValidators()`? Its value is incremented each time when the set of validators is changed or when the new staking epoch begins.

**Comment by varasev** [comment]
I think I could solve this on the contracts level though. Don't implement this yet, I'll try to fix it in the contracts tomorrow.

**Comment by varasev** [comment]
This was fixed in https://github.com/poanetwork/pos-contracts/commit/42201557194208ab10e0f5356ca9d0c39b017d30.

@DemiMarie please clarify, will the Parity trigger the validator set changing (and call `finalizeChange` as a result) if the `getPendingValidators()` returns the same validator set, but in the different order?

For example, `getPendingValidators()` returns the next validator set:
1. 0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe
2. 0xeE385a1df869A468883107B0C06fA8791b28A04f
3. 0x71385ae87c4b93db96f02f952be1f7a63f6057a6

Then imagine that at some block it returns the same set but in another order:

1. 0x71385ae87c4b93db96f02f952be1f7a63f6057a6
2. 0x1092a1E3A3F2FB2024830Dd12064a4B33fF8EbAe
3. 0xeE385a1df869A468883107B0C06fA8791b28A04f

Will it be considered as a new set? (and call `finalizeChange()` as a result?)

**Comment by DemiMarie** [comment]
@varasev I am having trouble figuring out the answer, sorry.  The code in question is very confusing.

If the order doesn’t matter, I suggest explicitly sorting the return values in Rust code.

**Comment by DemiMarie** [comment]
@varasev Parity will call `finalizeChange` whenever it opens a block.

Can `finalizeChange` be made idempotent?  That way, excess calls will not be a problem.

**Comment by afck** [comment]
They are indeed [read](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/safe_contract.rs#L284) from the contract [in order](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/simple_list.rs#L29). And `AuthorityRound` [uses that order](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/authority_round/mod.rs#L563) to determine the current proposer. So I'd say yes, it does make a difference and the order matters.

However, there is currently no code that tries to detect validator set _changes_ at all, because there's nothing in Aura that's triggered by them: Calling `newValidatorSet()` is done by the block reward contract itself now, is it? I'm not sure about [`finalizeChange()`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/safe_contract.rs#L305): It's called in [`AuthorityRound::on_new_block`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/authority_round/mod.rs#L1189) if `epoch_begin`. That is called in [`OpenBlock::new`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/block.rs#L288), with `is_epoch_begin` as an argument, which is called in lots of places…
The relevant one seems to be in [`Client::prepare_open_block`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/client/client.rs#L2270), where:
```rust
let is_epoch_begin = chain.epoch_transition(best_header.number(), h).is_some();
```
However, [`BlockChain::epoch_transition`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/blockchain/blockchain.rs#L963) seems to just look up some "transition candidates" into the `BlockChainDB`, and check whether the block hash is among them. It looks like the candidates are inserted using [`BlockChain::insert_epoch_transition`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/blockchain/blockchain.rs#L936), which is called in [`Client::check_epoch_end`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/client/client.rs#L680), which in turn calls [`AuthorityRound::is_epoch_end`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/authority_round/mod.rs#L1430).

[This comment and early return](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/authority_round/mod.rs#L1437) I don't understand at all: I think we always need to care for epochs??
Anyway, next `ValidatorSet::is_epoch_end` [is called](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/authority_round/mod.rs#L1443), and only if that returns `None`, some "store for pending transitions" is searched…

For some reason, [`SafeContract::is_epoch_end`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/safe_contract.rs#L316) (and therefore also [`Contract::is_epoch_end`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/contract.rs#L84)) always return `None`!

So back to the store of pending transitions: These are also [passed in by the caller](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/client/client.rs#L685), and in this case use [`Chain::get_pending_transition`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/blockchain/blockchain.rs#L1012). These are inserted with [`Chain::insert_pending_transition`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/blockchain/blockchain.rs#L1005), which in turn [is called](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/client/client.rs#L669) in [`Client::check_epoch_end_signal`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/client/client.rs#L586)—[_if_](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/client/client.rs#L604) a call to [`AuthorityRound::signals_epoch_end`](https://github.com/poanetwork/parity-ethereum/blob/aura-pos/ethcore/src/engines/authority_round/mod.rs#L1378) returns an `EpochChange::Yes(_)`. This again directly returns `No` if `self.immediate_transitions` is `true` for some reason, and otherwise delegates to `ValidatorSet::signals_epoch_end`, which [in](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/contract.rs#L88) our [case](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/safe_contract.rs#L320) [asks](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/safe_contract.rs#L350) [`extract_from_block`](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/safe_contract.rs#L280), which returns `Some` with the result of [`getPendingValidators`](https://github.com/poanetwork/pos-contracts/blob/6f149e98ea4ce822d890dc512e4d97b278212293/contracts/abstracts/ValidatorSetBase.sol#L218) using the default caller (Is that correct—is that for the current block?) unless that contract call failed!

So: **My guess is that we're calling `finalizeChange` in _every_ block, which is wrong and #49 would need to be reopened.**
@DemiMarie: Could you please have a look, too, and double-check?

**Comment by varasev** [comment]
> My guess is that we're calling finalizeChange in every block, which is wrong

Exactly, the `finalizeChange` definitely shouldn't be called every block - I've checked that with original version of Parity with a simple ValidatorSet contract.

The docs on https://wiki.parity.io/Validator-Set.html say that finalizeChange `Called when an initiated change reaches finality and is activated`.

And finalizeChange `Also called when the contract is first enabled for consensus` - it means that it is called once on the block number 1 (I checked that).

I repeat here just in case what I wrote in our Slack channel:

According to [Parity docs](https://wiki.parity.io/Validator-Set.html) and AFAIK the `finalizeChange` function is called by Parity in the next case by default:

1) some function of ValidatorSet smart contract emitted `InitiateChange` event with a new list of validators;

2) this event caught by Parity;

3) the new validator set applied on Parity side;

4) the `finalizeChange` is called to inform the ValidatorSet contract that the new list of validators (which was passed on the point 1) is applied by the engine.

According to https://github.com/poanetwork/parity-ethereum/issues/49 all we need to do is to use `getPendingValidators()` getter instead of `InitiateChange` event to know that the validator set is changed and to get the returned set.

I implemented the next fix in the contracts: https://github.com/poanetwork/parity-ethereum/issues/71#issue-401791736

In my implementation, the order of validators returned by `getPendingValidators()` has the meaning because if the order of validators changed in `getPendingValidators()` when new staking epoch starts, the contract treats this as the new set of validators and expects that Parity will call `finalizeChange` by itself.

If `getPendingValidators()` returns exactly the same set of validators in the same order when new staking epoch starts, the Parity engine won't call `finalizeChange()` because nothing is changed, so the contract will call this function by itself.

The contracts expect that the different order of the same set of validators in `getPendingValidators()` will trigger Parity to re-apply the set in the engine and call `finalizeChange` according to https://github.com/poanetwork/parity-ethereum/issues/49

I asked the question https://github.com/poanetwork/parity-ethereum/issues/71#issuecomment-457086255 to make sure that Parity will re-apply the inner set of validators and call `finalizeChange()` even when `getPendingValidators()` returns the same set of validators but in a different order.

**Comment by afck** [comment]
> all we need to do is to use `getPendingValidators()` getter instead of `InitiateChange`

Yes, that's the problem: Every block with an `InitiateChange` event means an epoch transition, but with `getPendingValidators`, we'd need to compare the result to the previous one, which wasn't done in #49, I think. Reopening…

**Comment by DemiMarie** [comment]
@afck I have not done tests, but from reading the code, it seems clear that `finalizeChange()` is being called every block.

Is there some reason that we cannot just use the `InitiateChange` event?  Or have `getPendingValidators()` fail when there is no epoch change?

**Comment by varasev** [comment]
> Is there some reason that we cannot just use the `InitiateChange` event?

We can't use `InitiateChange` event in `newValidatorSet()` because it is called by `BlockReward.reward()` which is called by SYSTEM_ADDRESS.

**Comment by afck** [comment]
Isn't that the old problem with the log events: that we're currently making the call that initiates the validator set change as a system call and not a transaction, so that it can't log events?

Would it be feasible to compare the returned validator list with the existing one [here](https://github.com/poanetwork/parity-ethereum/blob/c159028507b8a35e1e39d6c8a11f4c72bee0a27e/ethcore/src/engines/validator_set/safe_contract.rs#L350), and return `No` if they are identical? (Not sure how exactly the `validators` field works and what to do if there's no previous entry, though…)

**Comment by DemiMarie** [comment]
Another thought: can we make `getPendingValidators()` revert if called at the wrong time?

@varasev

**Comment by DemiMarie** [comment]
@afck I can try to figure out where to find the existing one.  It is feasible if and only if I can find the old validator set.

**Comment by varasev** [comment]
@DemiMarie It would be easier if we just used `changeRequestCount()` getter as a signal that `getPendingValidators()` should be called and the returned validator set should be applied with followed calling of `finalizeChange` by the engine (according to Parity docs).

The main thing is that the contract expects that `finalizeChange()` will always be called by the engine after `newValidatorSet()` is called and after the new validator set (returned by `getPendingValidators()`) is applied in Parity. Even when the validator set is not changed. Because `finalizeChange()` begins new staking epoch.

**Comment by varasev** [comment]
So, the algorithm must be the next, I think:

1. Check if `changeRequestCount()` is incremented.

2. If it is, call `getPendingValidators()` and get its returned validator set.

3. Pass this set of validators to Parity's routine where the `InitiateChange` event is handled (I don't know how and where it's implemented in Parity).

4. Parity then should apply the validator set and call `finalizeChange()` according to the docs https://wiki.parity.io/Validator-Set.html

**Comment by DemiMarie** [comment]
That way, I can just write a `hasValidatorSetChanged` function.

**Comment by varasev** [comment]
> @varasev is it okay for `newValidatorSet` to set a flag that is cleared on `finalizeChange`?

We already have such a flag:
- https://github.com/poanetwork/pos-contracts/blob/1a443bd3eaa7777089c226764bf5390b9ea9d59a/contracts/abstracts/ValidatorSetBase.sol#L590
- https://github.com/poanetwork/pos-contracts/blob/1a443bd3eaa7777089c226764bf5390b9ea9d59a/contracts/abstracts/ValidatorSetBase.sol#L119

> That way, I can just write a `hasValidatorSetChanged` function.

Parity should request and get the updated validator set in two cases:
1. a new staking epoch begins (i.e. right after `newValidatorSet()` is called);
2. a malicious validator is removed.

The [algorithm](https://github.com/poanetwork/parity-ethereum/issues/71#issuecomment-457208487) with `changeRequestCount()` I suggested above takes into account these two cases because the `changeRequestCount` value is incremented each time when the malicious validator is removed from the set or when `newValidatorSet()` is called.

Do you have a better idea?

**Comment by DemiMarie** [comment]
@varasev can we call `_setValidatorSetApplyBlock(0)` from `_banValidator(address)`?

**Comment by DemiMarie** [comment]
@varasev is it harmful to call `emitInitiateChange` when it is not necessary?

**Comment by DemiMarie** [comment]
@varasev does that mean that I can revert the changes in Parity about _not_ using `InitiateChange`?

**Comment by varasev** [comment]
> @varasev is it harmful to call `emitInitiateChange` when it is not necessary?

I've just added `emitInitiateChangeCallable()` getter: https://github.com/poanetwork/pos-contracts/commit/ca0b98040ed9d04b52b1ceabd2c6adc60d123d63 - if it returns `true`, the validator can call `emitInitiateChange`.

> @varasev does that mean that I can revert the changes in Parity about _not_ using `InitiateChange`?

Yes, we should revert all the changes made within https://github.com/poanetwork/parity-ethereum/issues/49.

**Comment by DemiMarie** [comment]
@varasev Can `emitInitiateChange` just be a no-op if `emitInitiateChangeCallable()` returns `false`?  That would save some work on the Parity side.

**Comment by varasev** [comment]
@DemiMarie Yes, in the case when there is nothing to do, `emitInitiateChange` function [just `return`](https://github.com/poanetwork/pos-contracts/blob/ca0b98040ed9d04b52b1ceabd2c6adc60d123d63/contracts/abstracts/ValidatorSetBase.sol#L94) and does nothing, but the corresponding transaction calling this functions, of course, will be mined anyway.

We could replace `return`s with `require`s if that is necessary for Parity code. For example:

```solidity
    function emitInitiateChange() external {
        require(isValidator(msg.sender));
        require(emitInitiateChangeCallable());
        (address[] memory newSet, bool newStakingEpoch) = _dequeuePendingValidators();
        if (newSet.length > 0) {
            emit InitiateChange(blockhash(block.number - 1), newSet);
            _setInitiateChangeAllowed(false);
            _setQueueValidators(newSet, newStakingEpoch);
        }
    }
```

In this case the function will `revert` if there is nothing to do.

**Comment by afck** [comment]
That would be great: We wouldn't need to change the epoch transition code. :+1: 
My only concerns are:
* With our current method of making service transactions (putting them into the queue, like we already do for the randomness contract), is it guaranteed that the transaction actually makes it into the _current_ block?
* Does that even work in `on_close_block`, when the block's gas limit may already have been reached? Can and should we make the call in `on_new_block` instead?
* Unlike system calls, which are implicit, these are now explicit transactions, and we need to enforce that the block authors make them. Ideally, we should make a block invalid if `emitInitiateChange` hasn't been called but should have been. At least we should report the author as malicious in that case.

(So: Maybe this approach just works, and is easiest to implement; but we need to dig through the Parity code to make sure these three points are fine.)

**Comment by varasev** [comment]
> With our current method of making service transactions (putting them into the queue, like we already do for the randomness contract), is it guaranteed that the transaction actually makes it into the current block?

I think there is nothing wrong if the calling of `emitInitiateChange()` will be made on the next block after the current or even on the block after the next because it's not time critical operation.

> Does that even work in `on_close_block`, when the block's gas limit may already have been reached? Can and should we make the call in `on_new_block` instead?

Yes, it's better to make the call in `on_new_block`, imho. Because the service transaction consumes the gas as the regular transaction and takes into account the gas limit of the block. By the way, the same goes for RandomAuRa functions (`commitHash` and `revealSecret`).

> Unlike system calls, which are implicit, these are now explicit transactions, and we need to enforce that the block authors make them. Ideally, we should make a block invalid if `emitInitiateChange` hasn't been called but should have been. At least we should report the author as malicious in that case.

Ideally yes, it's a good idea. But if the current validator doesn't call `emitInitiateChange`, the next validator (which is honest) can make the call.

**Comment by varasev** [comment]
> My understanding is that _somebody_ needs to call `emitInitateChange`, but the network will be okay as log as _any_ of the validators do it. Is that accurate?

Actually, we don't need the next condition: https://github.com/poanetwork/pos-contracts/blob/ca0b98040ed9d04b52b1ceabd2c6adc60d123d63/contracts/abstracts/ValidatorSetBase.sol#L93

I removed that: https://github.com/poanetwork/pos-contracts/commit/19a413638c474153d43a6a8fd523d7417492231b

So, now anybody (not only validator) can call `emitInitiateChange`.

> Could it be (say) called as a side-effect of the calls to the randomness contract?

The `RandomAuRa.commitHash` and `RandomAuRa.revealSecret` functions are called by validators not every block according to https://github.com/poanetwork/parity-ethereum/issues/51. There can be a big gap between callings, so this proposal doesn't suit for calling `emitInitiateChange`. The `emitInitiateChange` needs to be called separately: each validator should call `emitInitiateChange` function on his turn (ideally when he produces a block).

**Comment by afck** [comment]
Right, so for now we should just make a constant call to `emitInitiateChangeCallable`, and if that's `true`, a transaction call to `emitInitiateChange`, both in `on_new_block` and with the [same method*](https://github.com/poanetwork/parity-ethereum/blob/288362b79de406301bcbfb04f604cd6184090041/ethcore/src/engines/authority_round/util.rs#L18) as for the randomness contract for now. I'd prefer to make the constant call explicitly (even if it happens inside `emitInitiateChange` again), because otherwise we'd add a no-op transaction to each block where it's `false`.

(*) I still suspect that this is an unnecessary indirection and there's probably a more direct way to add the transaction to the current open block without adding it to the queue, but I haven't quite figured that out yet.

**Comment by DemiMarie** [comment]
Fixed.
